/**
 * Extended phone data for listing and comparison pages
 * UAE-focused with realistic pricing and DECISION-FOCUSED attributes
 */

export const allPhones = [
  {
    id: "1",
    slug: "samsung-galaxy-a35-5g",
    name: "Samsung Galaxy A35 5G",
    brand: "Samsung",
    image: "/mobile1.jpg",
    price: 1199,
    priceRange: "AED 1,199",
    releaseDate: "2024-03",
    category: "mid-range",
    // Decision-focused attributes
    badge: "Best Battery Life",
    badgeColor: "emerald",
    whyPick: "Longest battery life in this price range with 4 years of updates",
    bestFor: ["battery", "daily-use", "updates"],
    verdict: "Perfect for users who prioritize battery and software longevity over camera",
    overallScore: { rating: 8.1, label: "Very Good" },
    scores: {
      camera: 7,
      battery: 9,
      performance: 7,
      display: 8,
      value: 8,
    },
    highlights: ["AMOLED 120Hz", "5000mAh Battery", "IP67 Water Resistant"],
    pros: ["All-day battery", "4 years updates", "Great display"],
    cons: ["Average camera", "Plastic build"],
    specs: {
      display: "6.6\" Super AMOLED 120Hz",
      processor: "Exynos 1380",
      ram: "8GB",
      storage: "128GB/256GB",
      camera: "50MP + 8MP + 5MP",
      battery: "5000mAh",
      charging: "25W",
      os: "Android 14",
    },
    tags: ["5g", "amoled", "good-battery", "water-resistant"],
  },
  {
    id: "2",
    slug: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    image: "/mobile1.jpg",
    price: 5299,
    priceRange: "AED 5,299",
    releaseDate: "2023-09",
    category: "flagship",
    badge: "Best for Video",
    badgeColor: "blue",
    whyPick: "Unmatched video quality and best-in-class ecosystem integration",
    bestFor: ["video", "ecosystem", "resale"],
    verdict: "The ultimate iPhone for content creators who shoot video",
    overallScore: { rating: 9.2, label: "Excellent" },
    scores: {
      camera: 10,
      battery: 9,
      performance: 10,
      display: 10,
      value: 7,
    },
    highlights: ["A17 Pro Chip", "Titanium Design", "5x Optical Zoom"],
    pros: ["Best video quality", "Titanium build", "7 years updates"],
    cons: ["Expensive", "No USB-C accessories included"],
    specs: {
      display: "6.7\" Super Retina XDR 120Hz",
      processor: "A17 Pro",
      ram: "8GB",
      storage: "256GB/512GB/1TB",
      camera: "48MP + 12MP + 12MP",
      battery: "4422mAh",
      charging: "27W",
      os: "iOS 17",
    },
    tags: ["5g", "flagship", "best-camera", "premium"],
  },
  {
    id: "3",
    slug: "samsung-galaxy-s24-ultra",
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    image: "/mobile1.jpg",
    price: 4999,
    priceRange: "AED 4,999",
    releaseDate: "2024-01",
    category: "flagship",
    badge: "Best Camera Phone",
    badgeColor: "purple",
    whyPick: "200MP camera with AI features and built-in S Pen for productivity",
    bestFor: ["camera", "productivity", "ai"],
    verdict: "Best Android flagship for photography enthusiasts and power users",
    overallScore: { rating: 9.4, label: "Excellent" },
    scores: {
      camera: 10,
      battery: 9,
      performance: 10,
      display: 10,
      value: 8,
    },
    highlights: ["200MP Camera", "S Pen Included", "Titanium Frame"],
    pros: ["Best zoom camera", "S Pen included", "7 years updates"],
    cons: ["Large and heavy", "Expensive"],
    specs: {
      display: "6.8\" Dynamic AMOLED 2X 120Hz",
      processor: "Snapdragon 8 Gen 3",
      ram: "12GB",
      storage: "256GB/512GB/1TB",
      camera: "200MP + 50MP + 12MP + 10MP",
      battery: "5000mAh",
      charging: "45W",
      os: "Android 14",
    },
    tags: ["5g", "flagship", "best-camera", "s-pen", "premium"],
  },
  {
    id: "4",
    slug: "google-pixel-8-pro",
    name: "Google Pixel 8 Pro",
    brand: "Google",
    image: "/mobile1.jpg",
    price: 3799,
    priceRange: "AED 3,799",
    releaseDate: "2023-10",
    category: "flagship",
    badge: "Best AI Features",
    badgeColor: "sky",
    whyPick: "Most advanced AI camera and 7 years of guaranteed updates",
    bestFor: ["ai", "updates", "photography"],
    verdict: "Best for AI enthusiasts who want the purest Android experience",
    overallScore: { rating: 8.9, label: "Excellent" },
    scores: {
      camera: 10,
      battery: 8,
      performance: 9,
      display: 9,
      value: 8,
    },
    highlights: ["Best-in-class AI", "7 Years Updates", "Magic Eraser"],
    pros: ["AI photo editing", "Pure Android", "Amazing night photos"],
    cons: ["Smaller battery", "Limited availability in UAE"],
    specs: {
      display: "6.7\" LTPO OLED 120Hz",
      processor: "Tensor G3",
      ram: "12GB",
      storage: "128GB/256GB/512GB",
      camera: "50MP + 48MP + 48MP",
      battery: "5050mAh",
      charging: "30W",
      os: "Android 14",
    },
    tags: ["5g", "flagship", "best-camera", "ai-features"],
  },
  {
    id: "5",
    slug: "xiaomi-14-pro",
    name: "Xiaomi 14 Pro",
    brand: "Xiaomi",
    image: "/mobile1.jpg",
    price: 3499,
    priceRange: "AED 3,499",
    releaseDate: "2024-02",
    category: "flagship",
    badge: "Best Fast Charging",
    badgeColor: "orange",
    whyPick: "Flagship specs with Leica camera at a more accessible price",
    bestFor: ["charging", "camera", "value"],
    verdict: "Best value flagship with 120W charging and Leica optics",
    overallScore: { rating: 8.7, label: "Very Good" },
    scores: {
      camera: 9,
      battery: 8,
      performance: 10,
      display: 9,
      value: 9,
    },
    highlights: ["Leica Camera", "120W Charging", "Snapdragon 8 Gen 3"],
    pros: ["120W ultra-fast charging", "Leica camera", "Great value"],
    cons: ["MIUI learning curve", "No wireless charging"],
    specs: {
      display: "6.73\" LTPO AMOLED 120Hz",
      processor: "Snapdragon 8 Gen 3",
      ram: "12GB",
      storage: "256GB/512GB",
      camera: "50MP + 50MP + 50MP",
      battery: "4880mAh",
      charging: "120W",
      os: "Android 14",
    },
    tags: ["5g", "flagship", "fast-charging", "leica"],
  },
  {
    id: "6",
    slug: "oneplus-12",
    name: "OnePlus 12",
    brand: "OnePlus",
    image: "/mobile1.jpg",
    price: 3299,
    priceRange: "AED 3,299",
    releaseDate: "2024-01",
    category: "flagship",
    badge: "Best Value Flagship",
    badgeColor: "emerald",
    whyPick: "Flagship performance at mid-range price with incredible battery",
    bestFor: ["value", "battery", "performance"],
    verdict: "Best flagship for users who want top specs without paying Apple/Samsung prices",
    overallScore: { rating: 8.6, label: "Very Good" },
    scores: {
      camera: 8,
      battery: 9,
      performance: 10,
      display: 9,
      value: 9,
    },
    highlights: ["100W SUPERVOOC", "Hasselblad Camera", "5400mAh Battery"],
    pros: ["Massive battery", "Fast charging", "Smooth OxygenOS"],
    cons: ["Camera not as good as competition", "Curved display"],
    specs: {
      display: "6.82\" LTPO AMOLED 120Hz",
      processor: "Snapdragon 8 Gen 3",
      ram: "12GB/16GB",
      storage: "256GB/512GB",
      camera: "50MP + 48MP + 64MP",
      battery: "5400mAh",
      charging: "100W",
      os: "Android 14",
    },
    tags: ["5g", "flagship", "fast-charging", "good-battery"],
  },
  {
    id: "7",
    slug: "samsung-galaxy-a55-5g",
    name: "Samsung Galaxy A55 5G",
    brand: "Samsung",
    image: "/mobile1.jpg",
    price: 1699,
    priceRange: "AED 1,699",
    releaseDate: "2024-03",
    category: "mid-range",
    badge: "Best Mid-Range Overall",
    badgeColor: "blue",
    whyPick: "Premium build quality with flagship-like features at mid-range price",
    bestFor: ["balanced", "updates", "build-quality"],
    verdict: "Best all-rounder for users who want Samsung quality without flagship price",
    overallScore: { rating: 8.3, label: "Very Good" },
    scores: {
      camera: 8,
      battery: 8,
      performance: 8,
      display: 9,
      value: 8,
    },
    highlights: ["Super AMOLED 120Hz", "Metal Frame", "5000mAh"],
    pros: ["Metal frame", "Great display", "4 years updates"],
    cons: ["Slower charging", "No telephoto"],
    specs: {
      display: "6.6\" Super AMOLED 120Hz",
      processor: "Exynos 1480",
      ram: "8GB",
      storage: "128GB/256GB",
      camera: "50MP + 12MP + 5MP",
      battery: "5000mAh",
      charging: "25W",
      os: "Android 14",
    },
    tags: ["5g", "amoled", "good-battery", "mid-range"],
  },
  {
    id: "8",
    slug: "xiaomi-redmi-note-13-pro",
    name: "Xiaomi Redmi Note 13 Pro",
    brand: "Xiaomi",
    image: "/mobile1.jpg",
    price: 1099,
    priceRange: "AED 1,099",
    releaseDate: "2024-01",
    category: "budget",
    badge: "Best Budget Camera",
    badgeColor: "purple",
    whyPick: "200MP camera at an unbelievable price point",
    bestFor: ["camera", "budget", "value"],
    verdict: "Best for budget users who prioritize camera quality",
    overallScore: { rating: 7.8, label: "Good" },
    scores: {
      camera: 8,
      battery: 8,
      performance: 7,
      display: 8,
      value: 9,
    },
    highlights: ["200MP Camera", "AMOLED 120Hz", "67W Turbo Charging"],
    pros: ["Amazing 200MP camera", "Great value", "Fast charging"],
    cons: ["Average processor", "MIUI ads"],
    specs: {
      display: "6.67\" AMOLED 120Hz",
      processor: "Snapdragon 7s Gen 2",
      ram: "8GB",
      storage: "256GB",
      camera: "200MP + 8MP + 2MP",
      battery: "5100mAh",
      charging: "67W",
      os: "Android 14",
    },
    tags: ["5g", "budget", "good-camera", "fast-charging"],
  },
  {
    id: "9",
    slug: "realme-12-pro-plus",
    name: "Realme 12 Pro+",
    brand: "Realme",
    image: "/mobile1.jpg",
    price: 1599,
    priceRange: "AED 1,599",
    releaseDate: "2024-02",
    category: "mid-range",
    badge: "Best Telephoto Budget",
    badgeColor: "orange",
    whyPick: "Only phone under AED 2,000 with a periscope telephoto lens",
    bestFor: ["telephoto", "camera", "value"],
    verdict: "Best for users who want zoom photography without flagship prices",
    overallScore: { rating: 7.9, label: "Good" },
    scores: {
      camera: 8,
      battery: 8,
      performance: 7,
      display: 8,
      value: 8,
    },
    highlights: ["Periscope Telephoto", "Curved Display", "67W Charging"],
    pros: ["Periscope lens", "Premium design", "Good value"],
    cons: ["Slower processor", "Software updates uncertain"],
    specs: {
      display: "6.7\" AMOLED 120Hz",
      processor: "Snapdragon 7s Gen 2",
      ram: "8GB/12GB",
      storage: "256GB",
      camera: "50MP + 64MP + 8MP",
      battery: "5000mAh",
      charging: "67W",
      os: "Android 14",
    },
    tags: ["5g", "mid-range", "telephoto", "fast-charging"],
  },
  {
    id: "10",
    slug: "nothing-phone-2a",
    name: "Nothing Phone (2a)",
    brand: "Nothing",
    image: "/mobile1.jpg",
    price: 1399,
    priceRange: "AED 1,399",
    releaseDate: "2024-03",
    category: "mid-range",
    badge: "Most Unique Design",
    badgeColor: "slate",
    whyPick: "Stand out from the crowd with unique Glyph lights and clean software",
    bestFor: ["design", "clean-os", "unique"],
    verdict: "Best for users who want something different from boring phone designs",
    overallScore: { rating: 8.0, label: "Very Good" },
    scores: {
      camera: 7,
      battery: 8,
      performance: 8,
      display: 8,
      value: 9,
    },
    highlights: ["Glyph Interface", "Clean OS", "Unique Design"],
    pros: ["Unique Glyph lights", "Clean software", "Great value"],
    cons: ["Average camera", "Limited service centers"],
    specs: {
      display: "6.7\" AMOLED 120Hz",
      processor: "Dimensity 7200 Pro",
      ram: "8GB/12GB",
      storage: "128GB/256GB",
      camera: "50MP + 50MP",
      battery: "5000mAh",
      charging: "45W",
      os: "Nothing OS 2.5",
    },
    tags: ["5g", "mid-range", "unique-design", "clean-os"],
  },
  {
    id: "11",
    slug: "oppo-find-x7-ultra",
    name: "OPPO Find X7 Ultra",
    brand: "OPPO",
    image: "/mobile1.jpg",
    price: 4299,
    priceRange: "AED 4,299",
    releaseDate: "2024-01",
    category: "flagship",
    badge: "Best Zoom Camera",
    badgeColor: "purple",
    whyPick: "Dual periscope cameras for unmatched zoom photography",
    bestFor: ["zoom", "camera", "photography"],
    verdict: "Best for serious photographers who need extreme zoom capabilities",
    overallScore: { rating: 8.8, label: "Excellent" },
    scores: {
      camera: 10,
      battery: 8,
      performance: 9,
      display: 9,
      value: 8,
    },
    highlights: ["Dual Periscope", "Hasselblad Tuning", "100W SUPERVOOC"],
    pros: ["Dual periscope lenses", "Hasselblad colors", "Fast charging"],
    cons: ["Large phone", "ColorOS learning curve"],
    specs: {
      display: "6.82\" LTPO AMOLED 120Hz",
      processor: "Snapdragon 8 Gen 3",
      ram: "16GB",
      storage: "256GB/512GB",
      camera: "50MP + 50MP + 50MP + 50MP",
      battery: "5000mAh",
      charging: "100W",
      os: "ColorOS 14",
    },
    tags: ["5g", "flagship", "best-camera", "fast-charging"],
  },
  {
    id: "12",
    slug: "vivo-x100-pro",
    name: "Vivo X100 Pro",
    brand: "Vivo",
    image: "/mobile1.jpg",
    price: 3999,
    priceRange: "AED 3,999",
    releaseDate: "2024-01",
    category: "flagship",
    badge: "Best Portrait Camera",
    badgeColor: "rose",
    whyPick: "Zeiss optics with 1-inch sensor for professional-grade portraits",
    bestFor: ["portrait", "camera", "video"],
    verdict: "Best for portrait photographers and videographers",
    overallScore: { rating: 8.7, label: "Very Good" },
    scores: {
      camera: 10,
      battery: 8,
      performance: 9,
      display: 9,
      value: 8,
    },
    highlights: ["Zeiss Optics", "1\" Sensor", "100W Fast Charging"],
    pros: ["1-inch sensor", "Zeiss bokeh", "Great video"],
    cons: ["Heavy phone", "Funtouch OS less refined"],
    specs: {
      display: "6.78\" LTPO AMOLED 120Hz",
      processor: "Dimensity 9300",
      ram: "12GB/16GB",
      storage: "256GB/512GB",
      camera: "50MP + 50MP + 50MP",
      battery: "5400mAh",
      charging: "100W",
      os: "Funtouch OS 14",
    },
    tags: ["5g", "flagship", "best-camera", "fast-charging"],
  },
  {
    id: "13",
    slug: "iphone-15",
    name: "iPhone 15",
    brand: "Apple",
    image: "/mobile1.jpg",
    price: 3399,
    priceRange: "AED 3,399",
    releaseDate: "2023-09",
    category: "flagship",
    badge: "Best Compact Flagship",
    badgeColor: "blue",
    whyPick: "Most pocketable flagship with USB-C and Dynamic Island",
    bestFor: ["compact", "ecosystem", "one-hand"],
    verdict: "Best for users who want flagship features in a one-hand-friendly size",
    overallScore: { rating: 8.5, label: "Very Good" },
    scores: {
      camera: 9,
      battery: 8,
      performance: 9,
      display: 9,
      value: 7,
    },
    highlights: ["Dynamic Island", "48MP Main Camera", "USB-C"],
    pros: ["Compact size", "USB-C finally", "Great photos"],
    cons: ["60Hz display", "Slower charging"],
    specs: {
      display: "6.1\" Super Retina XDR",
      processor: "A16 Bionic",
      ram: "6GB",
      storage: "128GB/256GB/512GB",
      camera: "48MP + 12MP",
      battery: "3349mAh",
      charging: "20W",
      os: "iOS 17",
    },
    tags: ["5g", "flagship", "compact", "premium"],
  },
  {
    id: "14",
    slug: "samsung-galaxy-z-fold-5",
    name: "Samsung Galaxy Z Fold 5",
    brand: "Samsung",
    image: "/mobile1.jpg",
    price: 6799,
    priceRange: "AED 6,799",
    releaseDate: "2023-08",
    category: "flagship",
    badge: "Best for Multitasking",
    badgeColor: "indigo",
    whyPick: "Tablet-sized screen in your pocket for ultimate productivity",
    bestFor: ["multitasking", "productivity", "innovation"],
    verdict: "Best for power users who want a phone AND tablet in one device",
    overallScore: { rating: 8.8, label: "Excellent" },
    scores: {
      camera: 8,
      battery: 7,
      performance: 10,
      display: 10,
      value: 6,
    },
    highlights: ["Foldable 7.6\" Display", "Flex Mode", "IPX8 Water Resistant"],
    pros: ["Huge inner screen", "Great for multitasking", "S Pen support"],
    cons: ["Very expensive", "Heavy", "Visible crease"],
    specs: {
      display: "7.6\" Dynamic AMOLED 2X (Foldable)",
      processor: "Snapdragon 8 Gen 2",
      ram: "12GB",
      storage: "256GB/512GB/1TB",
      camera: "50MP + 12MP + 10MP",
      battery: "4400mAh",
      charging: "25W",
      os: "Android 14",
    },
    tags: ["5g", "foldable", "premium", "multitasking"],
  },
  {
    id: "15",
    slug: "poco-f6-pro",
    name: "POCO F6 Pro",
    brand: "Xiaomi",
    image: "/mobile1.jpg",
    price: 1999,
    priceRange: "AED 1,999",
    releaseDate: "2024-05",
    category: "mid-range",
    badge: "Best Gaming Value",
    badgeColor: "red",
    whyPick: "Flagship Snapdragon 8 Gen 2 at mid-range price for gamers",
    bestFor: ["gaming", "performance", "value"],
    verdict: "Best for mobile gamers who want flagship performance without flagship price",
    overallScore: { rating: 8.4, label: "Very Good" },
    scores: {
      camera: 7,
      battery: 8,
      performance: 10,
      display: 9,
      value: 10,
    },
    highlights: ["Snapdragon 8 Gen 2", "120W HyperCharge", "Gaming Beast"],
    pros: ["Flagship chip", "120W charging", "Great for gaming"],
    cons: ["Average camera", "POCO branding"],
    specs: {
      display: "6.67\" AMOLED 120Hz",
      processor: "Snapdragon 8 Gen 2",
      ram: "12GB/16GB",
      storage: "256GB/512GB",
      camera: "50MP + 8MP + 2MP",
      battery: "5000mAh",
      charging: "120W",
      os: "Android 14",
    },
    tags: ["5g", "gaming", "fast-charging", "best-value"],
  },
  {
    id: "16",
    slug: "honor-magic-6-pro",
    name: "Honor Magic 6 Pro",
    brand: "Honor",
    image: "/mobile1.jpg",
    price: 3899,
    priceRange: "AED 3,899",
    releaseDate: "2024-03",
    category: "flagship",
    badge: "Best Battery Flagship",
    badgeColor: "emerald",
    whyPick: "Largest battery in any flagship with innovative eye-tracking tech",
    bestFor: ["battery", "innovation", "camera"],
    verdict: "Best for heavy users who need all-day battery without compromises",
    overallScore: { rating: 8.6, label: "Very Good" },
    scores: {
      camera: 9,
      battery: 10,
      performance: 9,
      display: 9,
      value: 8,
    },
    highlights: ["Eye Tracking", "5600mAh Battery", "Falcon Camera"],
    pros: ["Massive 5600mAh battery", "Eye tracking", "Great camera"],
    cons: ["MagicOS learning curve", "Heavy phone"],
    specs: {
      display: "6.8\" LTPO OLED 120Hz",
      processor: "Snapdragon 8 Gen 3",
      ram: "12GB/16GB",
      storage: "256GB/512GB",
      camera: "50MP + 180MP + 50MP",
      battery: "5600mAh",
      charging: "80W",
      os: "MagicOS 8.0",
    },
    tags: ["5g", "flagship", "good-battery", "ai-features"],
  },
];

// Goal-based filters for decision-making
export const goalFilters = [
  { id: "camera", label: "📸 Best Camera", icon: "Camera", description: "Great for photography" },
  { id: "battery", label: "🔋 Long Battery", icon: "Battery", description: "All-day usage" },
  { id: "gaming", label: "🎮 Gaming", icon: "Gamepad", description: "Smooth gameplay" },
  { id: "value", label: "💰 Best Value", icon: "BadgeDollarSign", description: "Most for your money" },
  { id: "compact", label: "📱 Compact Size", icon: "Smartphone", description: "Easy one-hand use" },
  { id: "updates", label: "🔄 Long Updates", icon: "RefreshCw", description: "Future-proof" },
];

// Helper functions
export function getPhoneBySlug(slug) {
  return allPhones.find((phone) => phone.slug === slug);
}

export function getPhonesByBrand(brand) {
  return allPhones.filter(
    (phone) => phone.brand.toLowerCase() === brand.toLowerCase()
  );
}

export function getPhonesByPriceRange(min, max) {
  return allPhones.filter((phone) => phone.price >= min && phone.price <= max);
}

export function getPhonesByCategory(category) {
  return allPhones.filter((phone) => phone.category === category);
}

export function getPhonesByGoal(goal) {
  return allPhones
    .filter((phone) => phone.bestFor?.includes(goal))
    .sort((a, b) => (b.overallScore?.rating || 0) - (a.overallScore?.rating || 0));
}

export function getBrands() {
  return [...new Set(allPhones.map((phone) => phone.brand))];
}

export function getPriceRange() {
  const prices = allPhones.map((phone) => phone.price);
  return {
    min: Math.min(...prices),
    max: Math.max(...prices),
  };
}

// Comparison helper - generates verdict
export function generateComparisonVerdict(phones) {
  if (phones.length < 2) return null;

  const [phone1, phone2] = phones;
  const score1 = phone1.overallScore?.rating || 0;
  const score2 = phone2.overallScore?.rating || 0;

  const winner = score1 >= score2 ? phone1 : phone2;
  const loser = score1 >= score2 ? phone2 : phone1;

  // Find where each phone excels
  const phone1Wins = [];
  const phone2Wins = [];

  const categories = ['camera', 'battery', 'performance', 'display', 'value'];
  for (const cat of categories) {
    const s1 = phone1.scores?.[cat] || 0;
    const s2 = phone2.scores?.[cat] || 0;
    if (s1 > s2) phone1Wins.push(cat);
    else if (s2 > s1) phone2Wins.push(cat);
  }

  return {
    winner,
    loser,
    phone1Wins,
    phone2Wins,
    summary: `${winner.name} wins overall with better ${phone1Wins.length > phone2Wins.length ? phone1Wins.slice(0, 2).join(' and ') : phone2Wins.slice(0, 2).join(' and ')}`
  };
}
